POSManagementProject/Models/EntityModels/ItemCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace POSManagementProject.Models.EntityModels
{
    public class ItemCategory
    {
        public long Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Code { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public DateTime Date { get; set; }
        public long? ParentId { get; set; }
        public virtual ItemCategory Parent { get; set; }
    }
}

POSManagementProject/Controllers/ItemCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using POSManagementProject.DAL;
using POSManagementProject.Models.Context;
using POSManagementProject.Models.EntityModels;
using POSManagementProject.Models.ViewModels;
using System.Net;

namespace POSManagementProject.Controllers
{
    public class ItemCategoryController : Controller
    {
        ItemCategoryDAL itemCategoryDa = new ItemCategoryDAL();
        ItemCategoryVM ModelVm = new ItemCategoryVM();
        ImageData imageData = new ImageData();

        // GET: ItemCategory
        public ActionResult Index()
        {
            ModelVm.ItemCategories = itemCategoryDa.GetItemCategoryList().OrderByDescending(x => x.Date).ToList();
            return View(ModelVm.ItemCategories);
        }

        public ActionResult Create()
        {
            ModelVm.SelectList = itemCategoryDa.GetItemCategorySelectList();
            ModelVm.Code = itemCategoryDa.GetItemCategoryCode();
            return View(ModelVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemCategoryVM itemVm, HttpPostedFileBase ItemCategoryFile)
        {
            itemVm.Date = DateTime.Now;
            itemVm.Image = imageData.ImageConvertToByte(ItemCategoryFile);
            if (ModelState.IsValid)
            {
                if (itemCategoryDa.IsItemCategorySaved(itemVm))
                {
                    return RedirectToAction("Index");
                }
            }

            ModelVm.SelectList = itemCategoryDa.GetItemCategorySelectList();
            ModelVm.Code = itemCategoryDa.GetItemCategoryCode();
            return View(ModelVm);
        }
        
        public ActionResult Details(long id)
        {
            ItemCategoryVM itemVm = itemCategoryDa.FindItemCategory(id);
            return PartialView("_Details", itemVm);
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ModelVm = itemCategoryDa.FindItemCategory(id);

            if (ModelVm == null)
            {
                return HttpNotFound();
            }

            ModelVm.SelectList = itemCategoryDa.GetItemCategorySelectList();
            return View(ModelVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ItemCategoryVM itemVm)
        {
            if (ModelState.IsValid)
            {
                if (itemCategoryDa.IsItemCategoryUpdated(itemVm))
                {
                    return RedirectToAction("Index");
                }
            }

            return View(itemVm);
        }

        public ActionResult Delete(long id)
        {
            var isDeleted = itemCategoryDa.IsItemCategoryDeleted(id);

            return Json(isDeleted,JsonRequestBehavior.AllowGet);
        }

        public ActionResult IsUniqueName(string Name, string initialName)
        {
            var isUnique = itemCategoryDa.IsUniqueName(Name, initialName);
            return Json(isUnique, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IsUniqueCode(string Code, string initialCode)
        {
            var isUnique = itemCategoryDa.IsUniqueCode(Code, initialCode);
            return Json(isUnique, JsonRequestBehavior.AllowGet);
        }

    }
}

POSManagementProject/Views/ItemCategory/Create.cshtml
@model POSManagementProject.Models.ViewModels.ItemCategoryVM

@{
    ViewBag.Title = "Create";
}

<h4>Item Category Create</h4>
<hr />


@using (Html.BeginForm("Create", "ItemCategory", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <div class="form-group">
                    <label class="radio-inline">
                        <input type="radio" name="categoryRadio" id="parent" value="parent" checked="checked"> Parent Category
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="categoryRadio" id="child" value="child"> Child Category
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group" id="parentGroup" style="display: none">
            @Html.LabelFor(model => model.ParentId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ParentId, Model.SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ItemCategoryFile" id="itemCategoryFile" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                <br />
                <img src="" alt="" id="itemCategoryFilePreview" class="img-responsive" width="200" height="200" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Project/Image.js"></script>
    <script src="~/Scripts/Project/ShowHideGroup.js"></script>
}

POSManagementProject/Views/ItemCategory/Edit.cshtml
@model POSManagementProject.Models.ViewModels.ItemCategoryVM

@{
    ViewBag.Title = "Edit";
}

<h4>Item Category Edit</h4>
<hr />


@using (Html.BeginForm("Edit", "ItemCategory", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Image)
        @Html.HiddenFor(model => model.Date)
        @Html.Hidden("initialName",@Model.Name)
        @Html.Hidden("initialCode",@Model.Code)
        
        <div class="form-group">
            @Html.LabelFor(model => model.ParentId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ParentId,Model.SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
}

POSManagementProject/Views/ItemCategory/Index.cshtml
@model IEnumerable<POSManagementProject.Models.EntityModels.ItemCategory>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("Add Item Category","Create",null,new {@class="btn btn-primary"})
<br/><br /><br/>

<table class="table table-striped table-hover table-bordered" id="itemCategoryTable">
    <thead>
    <tr>
        <th>@Html.DisplayName("SL")</th>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>@Html.DisplayNameFor(model => model.Code)</th>
        <th>@Html.DisplayNameFor(model => model.Date)</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    @{ int sl = 0; }
    @foreach (var item in Model)
    {
        sl++;
        <tr id="row_@sl">
            <td>@Html.DisplayFor(modelItem => sl)</td>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.Code)</td>
            <td>@Html.DisplayFor(modelItem => item.Date)</td>
            <td>
                <a class="btn btn-primary btn-sm" onclick="ItemCategoryDetails(@item.Id)"
                   href='#'>
                    <i class="fa fa-info-circle fa-lg"></i>
                </a>
                <a class="btn btn-success btn-sm"
                   href='@Url.Action("Edit", "ItemCategory", new {id = item.Id})'>
                    <i class="fa fa-pencil fa-lg"></i>
                </a>
                <a class="btn btn-danger btn-sm" onclick="ConfirmDeleteItemCategory(@item.Id,@sl)" 
                   href="#" >
                    <i class="fa fa-trash fa-lg"></i>
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

<!--Start Details Modal -->
<div class="modal fade" id="detailsModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-primary">Item Category Details</h3>
            </div>
            <div class="modal-body" id="detailsModalContent">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>
<!--End Details Modal -->

<!-- Start Delete Modal -->
<div class="modal fade" id="confirmDeleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-danger">Confirmation</h3>
            </div>
            <div class="modal-body text-center">
                <h5>Are you sure want to delete this item category ? </h5>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-danger" onclick="DeleteItemCategory()">Confirm</a>
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="hiddenItemCategoryId" />
<input type="hidden" id="hiddenItemCategorySl" />
<!-- End Delete Modal -->

<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet"/>

@section scripts
{
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#itemCategoryTable').DataTable();
        });
    </script>

    <script src="~/Scripts/Project/ItemCategory.js"></script>
}

POSManagementProject/Views/ItemCategory/_Details.cshtml
@model POSManagementProject.Models.ViewModels.ItemCategoryVM

<div class="row">
    <div class="col-md-4">
        @if (Model.Image != null)
        {
            <img src="data:image/jpg;base64,@Convert.ToBase64String(Model.Image)" class="img-responsive" width="150" height="150"/>
        }
        else
        {
            <img src="~/Images/product.png" class="img-responsive" width="150" height="150"/>
        }
    </div>
    <div class="col-md-8">
        <br />
        <h5>
            @Html.Label("Name : ")
            @Html.DisplayFor(model => model.Name)
        </h5>
        <h5>
            @Html.Label("Code : ")
            @Html.DisplayFor(model => model.Code)
        </h5>
    </div>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.ParentId, new {@class="control-label col-md-4"})
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Parent.Name)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Description)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Date)
    </span>
</div>