POSManagementProject/Models/EntityModels/ExpenseItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace POSManagementProject.Models.EntityModels
{
    public class ExpenseItem
    {
        public long Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string PreCode { get; set; }
        [Required]
        public string Code { get; set; }
        public string Description { get; set; }
        public DateTime Date { get; set; }
        [Required]
        public long CategoryId { get; set; }
        public virtual ExpenseCategory Category { get; set; }
    }
}

POSManagementProject/Controllers/ExpenseItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using POSManagementProject.DAL;
using POSManagementProject.Models.ViewModels;

namespace POSManagementProject.Controllers
{
    public class ExpenseItemController : Controller
    {
        ExpenseItemDAL expenseItemDa = new ExpenseItemDAL();
        ExpenseItemVM ModelVm = new ExpenseItemVM();

        // GET: ExpenseItem
        public ActionResult Index()
        {
            ModelVm.Items = expenseItemDa.GetExpenseItemList().OrderByDescending(x => x.Date).ToList();
            return View(ModelVm.Items);
        }

        public ActionResult Create()
        {
            ModelVm.SelectList = expenseItemDa.GetExpenseItemSelectList();
            return View(ModelVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExpenseItemVM itemVm)
        {
            itemVm.Date = DateTime.Now;

            if (ModelState.IsValid)
            {
                if (expenseItemDa.IsExpenseItemSaved(itemVm))
                {
                    return RedirectToAction("Index");
                }
            }

            ModelVm.SelectList = expenseItemDa.GetExpenseItemSelectList();
            return View(ModelVm);
        }


        public ActionResult Details(long id)
        {
            ExpenseItemVM itemVm = expenseItemDa.FindExpenseItem(id);
            return PartialView("_Details", itemVm);
        }

        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ModelVm = expenseItemDa.FindExpenseItem(id);

            if (ModelVm == null)
            {
                return HttpNotFound();
            }

            ModelVm.SelectList = expenseItemDa.GetExpenseItemSelectList();
            return View(ModelVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExpenseItemVM itemVm)
        {
            if (ModelState.IsValid)
            {
                if (expenseItemDa.IsExpenseItemUpdated(itemVm))
                {
                    return RedirectToAction("Index");
                }
            }

            return View(itemVm);
        }

        public ActionResult Delete(long id)
        {
            var isDeleted = expenseItemDa.IsExpenseItemDeleted(id);

            return Json(isDeleted, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetItemFullCode(long id)
        {
            var preCode = expenseItemDa.GetExpenseCategoryCode(id);
            var code = expenseItemDa.GetExpenseItemCode(id);
            return Json(new { preCode, code }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IsUniqueName(string Name, string initialName)
        {
            var isUnique = expenseItemDa.IsUniqueName(Name, initialName);
            return Json(isUnique, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IsUniqueCode(string PreCode, string Code, string initialPreCode, string initialCode)
        {
            var isUnique = expenseItemDa.IsUniqueCode(PreCode, Code, initialPreCode, initialCode);
            return Json(isUnique, JsonRequestBehavior.AllowGet);
        }
    }
}

POSManagementProject/Views/ExpenseItem/Create.cshtml
@model POSManagementProject.Models.ViewModels.ExpenseItemVM

@{
    ViewBag.Title = "Create";
}


<h4>Expense Item Create</h4>
<hr />


@using (Html.BeginForm("Create", "ExpenseItem", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryId, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.CategoryId, Model.SelectList, new { @class = "form-control", @id = "categoryId" })
                        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.TextBoxFor(model => model.PreCode, new {@class = "form-control", @id = "itemPreCode", @readonly = true})
                            </div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.Code, new { @class = "form-control", @id = "itemCode" })
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.Code, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            <div class="col-md-5"></div>
        </div>

    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Project/ExpenseItem.js"></script>
}

POSManagementProject/Views/ExpenseItem/Edit.cshtml
@model POSManagementProject.Models.ViewModels.ExpenseItemVM

@{
    ViewBag.Title = "Edit";
}


<h4>Expense Item Edit</h4>
<hr />


@using (Html.BeginForm("Edit", "ExpenseItem", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Date)
        @Html.Hidden("initialName", @Model.Name)
        @Html.Hidden("initialPreCode", @Model.PreCode)
        @Html.Hidden("initialCode", @Model.Code)

        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryId, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.CategoryId, Model.SelectList, new { @class = "form-control", @id = "categoryId" })
                        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Code, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.TextBoxFor(model => model.PreCode, new { @class = "form-control", @id = "itemPreCode", @readonly = true })
                            </div>
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.Code, new { @class = "form-control", @id = "itemCode" })
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input type="submit" value="Update" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            <div class="col-md-5"></div>
        </div>

    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Project/ExpenseItem.js"></script>
}

POSManagementProject/Views/ExpenseItem/Index.cshtml
@model IEnumerable<POSManagementProject.Models.EntityModels.ExpenseItem>

@{
    ViewBag.Title = "Index";
}

@Html.ActionLink("Add Expense Item", "Create", null, new { @class = "btn btn-primary" })
<br /><br /><br />

<table class="table table-striped table-hover table-bordered" id="itemTable">
    <thead>
        <tr>
            <th>@Html.DisplayName("SL")</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Code)</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{ int sl = 0; }
        @foreach (var item in Model)
        {
            sl++;
            <tr id="row_@sl">
                <td>@Html.DisplayFor(modelItem => sl)</td>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.PreCode)
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    <a class="btn btn-primary btn-sm" onclick="ItemDetails(@item.Id)"
                       href='#'>
                        <i class="fa fa-info-circle fa-lg"></i>
                    </a>
                    <a class="btn btn-success btn-sm"
                       href='@Url.Action("Edit", "ExpenseItem", new {id = item.Id})'>
                        <i class="fa fa-pencil fa-lg"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" onclick="ConfirmDeleteItem(@item.Id,@sl)"
                       href="#">
                        <i class="fa fa-trash fa-lg"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!--Start Details Modal -->
<div class="modal fade" id="detailsModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-primary">Expense Item Details</h3>
            </div>
            <div class="modal-body" id="detailsModalContent">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>
<!--End Details Modal -->
<!-- Start Delete Modal -->
<div class="modal fade" id="confirmDeleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="text-danger">Confirmation</h3>
            </div>
            <div class="modal-body text-center">
                <h5>Are you sure want to delete this expense item ? </h5>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-danger" onclick="DeleteItem()">Confirm</a>
                <a href="#" class="btn btn-default" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="hiddenItemId" />
<input type="hidden" id="hiddenItemSl" />
<!-- End Delete Modal -->

<link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />

@section scripts
{
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function(){
            $('#itemTable').DataTable();
        });
    </script>

    <script src="~/Scripts/Project/ExpenseItem.js"></script>
}

POSManagementProject/Views/ExpenseItem/_Details.cshtml
@model POSManagementProject.Models.ViewModels.ExpenseItemVM

<div class="row">
    <div class="col-md-12">
        <br />
        <h5>
            @Html.Label("Name : ")
            @Html.DisplayFor(model => model.Name)
        </h5>
        <h5>
            @Html.Label("Code : ")
            @Html.DisplayFor(model => model.PreCode)
            @Html.DisplayFor(model => model.Code)
        </h5>
    </div>
</div>
<hr />
<div class="form-group row">
    @Html.LabelFor(model => model.CategoryId, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Category.Name)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Description)
    </span>
</div>
<div class="form-group row">
    @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-4" })
    <span class="control-label col-md-8">
        @Html.DisplayFor(model => model.Date)
    </span>
</div>